config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/about", to: "pages#about"
  get "/contact", to: "pages#contact"

  resources :wish_lists do
    member do
      patch :like
    end
    #新增時需要wishlist的ID
    #寄生在wish_list 不用index 不用show/不要編輯功能  shallow: true打開就有這種功能
    resources :comments , shallow: true ,only: [:create , :destroy]
    # resources :comments ,only: [:new, :create ,:index]
  end

  #新增時不需wishlist的ID
  # resources :comments ,only: [:show, :edit ,destroy]


  resource :user, as: "users" do
    collection do
      get :login
    end
  end
  
  resource :session , only: [:create , :destroy]
  # get "/make_a_wish", to: "wish_list#card"
  # get "/new_wish" , to: "wish_list#new"
  # post "/catch_wish", to: "wish_list#create"
  # get "/wish_card_info/:id", to: "wish_list#show", as: "wish_card_info"
  # get "/wish_card_info/:id/edit", to: "wish_list#edit", as: "edit_wish_card_info"
  # patch "/update_catch_wish/:id/update", to: "wish_list#update", as: "update_wish_card_info"
  
  # delete "/wish_card_info/:id", to: "wish_list#delete", as: "delete_wish_card_info"

  root "wish_lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  acts_as_paranoid
  #validates
  validates :content ,presence: true

  # relationship
  belongs_to :user
  belongs_to :wish_list
  
end

app/models/like_wish_list.rb
class LikeWishList < ApplicationRecord
  belongs_to :wish_list
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  #validates
  validates :email, presence: true
  validates :password,
             confirmation: true,
             length: { minimum: 6 }

  before_create :encrypt_password

  #relationship
  has_many :wish_lists
  has_many :comments
  
  has_many :like_wish_lists
  has_many :liked_wish_lists, through: :like_wish_lists ,source: :wish_list
  # has_many :order


  # callbacks
  before_create :encrypt_password

  # class methods
  def self.login(email, password)
    hashed_password = Digest::SHA1.hexdigest("keke#{password.reverse}haha")
    find_by(email: email , password: hashed_password)
  end



  private 
  def encrypt_password
  self.password = Digest::SHA1.hexdigest("keke#{self.password.reverse}haha")
  end
end

app/models/wish_list.rb
class WishList < ApplicationRecord
  validates :title , presence: true
  validates :description , presence: true

  #scope
  # scopes :not_deleted , ->{where(deleted_at: nil)}
  # default_scopes {where(delete_time: nil)}

  #relationship
  belongs_to :user
  has_many :comments

  has_many :like_wish_lists
  has_many :liked_users ,through: :like_wish_lists ,source: :user


  acts_as_paranoid
  # def destroy
  #   update(delete_time: Time.current)
  # end

  def liked_by?(user)
    liked_users.include?(user)
  end
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  # include UserHelper
  helper_method :current_user , :user_sign_in?
  #寫在controller給helper還可以用這個方法

  private
  def record_not_found
    # render html: "找不到"
    render file: "#{Rails.root}/public/404.html", status: 404,layout: false
  end

  def current_user
    #memorization 記憶手法，出現過的東西在這個頁面留下實體變數
    @login_username ||=User.find_by(id: session[:user])
  end

  def user_sign_in?
    !!session[:user]
  end

  def authenticate_user!
    if not user_sign_in?
    redirect_to login_users_path ,alert:"請先登入帳號"
    end
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user! 
  before_action :find_wish_list, only: [:create]
  before_action :find_comment, only: [:destroy]
  
  def create
    @comment=@wish_list.comments.new(comment_params)

    if @comment.save
        # redirect_to wish_list_path(@wish_list),notice:"已留言"
      else
        redirect_to wish_list_path(@wish_list),alert:"請填寫留言"
      end
    
  end

  def destroy
    @comment.destroy
    # @comment.update(deleted_at: Time.current)
    # redirect_to wish_list_path(@comment.wish_list) ,notice:"刪除成功"
  end

  private

  def find_comment
    @comment = current_user.comments.find(params[:id])
  end

  def find_wish_list
    @wish_list = current_user.wish_lists.find(params[:wish_list_id])
  end

  def comment_params
    params.require(:comment).permit(:content).merge(user: current_user)
    # params.require(:comment).permit(:content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home
end

def about
end

def contact
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    email = params[:email]
    password = params[:password]

    user = User.login(email, password)

    if user
      session[:user] = user.id
      redirect_to root_path, notice: "登入成功"
    else
      redirect_to login_users_path, alert: "登入失敗"
    end
  end

  def destroy
    session[:user] = nil
    redirect_to root_path , notice: "已登出"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user=User.new
  end

  def create
    @user = User.new(clean_user_params)
    if @user.save
      redirect_to root_path, notice: "註冊成功"
    else
      render :new
    end
  end

  def login
  end

private
  def clean_user_params
    params.require(:user).permit(:nickname , :email , :password , :password_confirmation)
  end




end

app/controllers/wish_lists_controller.rb
class WishListsController < ApplicationController
before_action :authenticate_user! 
before_action :find_wish_list, only:[:show ,:edit ,:update ,:destroy,:like]

  
  def index
    # @wish_lists = current_user.wish_lists
    #過濾有寫刪除時間的
    @wish_lists = current_user.wish_lists.where(deleted_at: nil)

  end
 
  def new
    @wish_list = WishList.new
  end

  def create
    # @wish_list = WishList.new(clean_wish_list)
    # @wish_list.user_id = current_user
    
    @wish_list = current_user.wish_lists.new(clean_wish_list)

    if @wish_list.save
      redirect_to root_path , notice: "許願成功～～"
    else
      render :new
    end
  end

  def show
    @comment=Comment.new
    #把id 做反向(id 升序 ASC；降序 DESC)排序(order)
    @comments=@wish_list.comments.order(id: :desc)
  end

  def edit
    
  end

  def update
    if @wish_list.update(clean_wish_list)
      redirect_to root_path , notice: "修改成功～～"
    else
      render :edit
    end
  end

  def destroy
    # @wish_list.destroy
    @wish_list.update(deleted_at: Time.current)

    redirect_to root_path ,notice:"刪除成功"
  end

  def like
    if @wish_list.liked_by?(current_user)
      # 移除 like
      current_user.liked_wish_lists.delete(@wish_list)
      render json: { status: 'unliked' }
    else
      # 新增 like
      current_user.liked_wish_lists << @wish_list
      render json: { status: 'liked' }
    end
  end


private
  def find_wish_list
    @wish_list = current_user.wish_lists.find(params[:id])
    # @wish_list = current_user.wish_lists.find_by!(id: params[:id] , delete_time: nil)
  end

  def clean_wish_list
    params.require(:wish_list).permit( :title , :description)
  end

 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
  def current_user
    #memorization 記憶手法，出現過的東西在這個頁面留下實體變數
  @login_username ||=User.find_by(id: session[:user])
  end

  # def user_sign_in?
  #   !!session[:user]
  # end
end

app/helpers/wish_list_helper.rb
module WishListHelper
end

app/views/comments/_comment.html.erb
 

<li id="<%= dom_id(comment) %>">
  <%= comment.content %>
  <%= link_to "刪除", comment_path(comment),method:"delete" ,data:{confirm:"確定嗎？" ,remote: true} %>
</li>

app/views/comments/create.js.erb
var comments = document.querySelector(".comments")

<%# var li= `<%= render "comments/comment" , comment: @comment %>
<%# 也可以改成這樣 %>
<%# var li= `<%= render @comment %>
<%# 使用跳脫符號j配單雙括號 %>
var li= "<%= j render @comment %>"


comments.insertAdjacentHTML("afterbegin",li)

document.querySelector('#comment_content').value = ''

app/views/comments/destroy.js.erb
document.querySelector("li#<%= dom_id(@comment) %>").remove()

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WishSite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "/shared/navbar" %>
  <%= render "/shared/flash" %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>關於我們</h1>

<!-- <a href="/contact"> 聯絡</a> -->
<!-- <%= link_to "聯絡" , "contact" %> -->
<%= link_to "聯絡" , contact_path %>

app/views/pages/contact.html.erb
<h1>聯絡我們</h1>


<!-- <a href="/about"> 關於</a> -->
<!-- <%= link_to "關於" , "/about" %> -->
<%= link_to "關於" , about_path %>
<!-- 認證信應用，回傳指定地點
<%= link_to "關於" , about_url %>   -->

app/views/pages/home.html.erb
<h1>首頁</h1>

app/views/shared/_flash.html.erb
<% if flash.any? %>
    <div style="color: white ; background-color:blue">
      <%= notice %>
    </div>
    <div style="color: white ; background-color: red">
     <%= alert %>
    </div>
  <% end %>

app/views/shared/_navbar.html.erb
<% if user_sign_in? %>
<nav>
  <%= link_to "我的許願卡" , wish_lists_path %>
  <%= link_to "登出", session_path, method: "delete" %>
  <%= current_user.email %>
  </nav>
<% else %>
<nav>
  <%= link_to "註冊", new_users_path %>
  <%= link_to "登入", login_users_path %>
</nav>
<% end %>

app/views/users/login.html.erb
<h1>登入畫面</h1>


<%= form_with(url: session_path )do |f| %>
  <div>
  <%= f.label :email %>
  <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <%= f.submit "登入"%>

<% end %>

app/views/users/new.html.erb
<h1> 註冊 </h1>


<%= form_with model: @user do |f| %>
  <div>
    <%= f.label :nickname %>
    <%= f.text_field :nickname %>
  </div>

  <div>
  <%= f.label :email %>
  <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :確認密碼 %>
    <%= f.password_field :password_confirmation %>
  </div>

  <%= f.submit "註冊" %>

<% end %>

app/views/wish_list/edit_wish.html.erb
<h1>編輯許願卡</h1>

<%= form_for @wish_list , url: update_wish_card_info_path(@wish_list) , method:"patch" do |f| %> 
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <%= f.submit %>

<% end %>

app/views/wish_list/show_wish.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>這裡是卡片裡面</h>
   
    <section>
      <%= @wish_list.title %>
     </section>
   <section>
    <%= simple_format(@wish_list.description) %>
   </section>
   
    
</body>
</html>

app/views/wish_lists/_form.html.erb
<%= form_for wish_list do |f| %> 
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <%= f.submit %>

<% end %>

app/views/wish_lists/edit.html.erb
<h1>編輯許願卡</h1>

<%= render "form" , wish_list: @wish_list %>

app/views/wish_lists/index.html.erb
<h1>許願卡 清單</h1>

<%= link_to '新增許願卡' ,  new_wish_list_path %></br>

<% @wish_lists.each do |wish_list|%>

<li>
<%= link_to "編輯", edit_wish_list_path(wish_list) %>
<%= link_to "刪除", wish_list_path(wish_list),method:"delete",data:{confirm: "確定嗎？"}%>
<%= link_to wish_list.title, wish_list_path(wish_list) %>
</li>

<% end %>

app/views/wish_lists/new.html.erb
<h1>新增許願卡</h1>

<%= render "form" , wish_list: @wish_list %>

app/views/wish_lists/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>這裡是卡片裡面</h1>
   
    <section>
      <%= @wish_list.title %>
      <button id="like_btn" 
              data-controller="favorite-btn"
              data-action="click->favorite-btn#toggle"
              data-id="<%= @wish_list.id %>"
              data-liked="<%= @wish_list.liked_by?(current_user) %>" >
              <i class="fa-regular fa-heart" 
                data-favorite-btn-target="icon"></i>
      </button>
    </section>

    <section>
      <%= simple_format(@wish_list.description) %>
    </section>
   
   <%# 用AJAX方式送資料(rails 6之後) local: false ；或是給他data:{remote: true} %>
   <%# 為了節省網數效能，適用於一次要載入很多資料的更新（反正我前端有出來給你看了，後端要跑但是不用重抓） %>
    <%= form_with(model: @comment, url: wish_list_comments_path(@wish_list) ,data:{remote: true}) do |f| %>

      <div>
        <div>留言</div>
        <%= f.text_area :content %>
      </div>

      <%= f.submit "留言" %>
    <% end %>
     
    <%# <ul class="comments"> %>
      <%# <% @comments.each do |comment| %> 
        <%# <%= render "comments/comment" , comment: comment%> 
        <%# 不建議在回圈裡寫render，rails官方建議使用render collection %>
      <%# <% end %> 
    <%# </ul> %>

    <ul class="comments">
      <%# 所以變成這樣(為了節省記憶體) %>
      <%# <%= render partial: "comments/comment" , collection: @comments , as: :comment %> 
      <%# 再符合慣例的話，可以變成 %>
      <%= render @comments %>
    </ul>
      
   
    
</body>
</html>

<%# <script>
  const like_btn = document.querySelector("#like_btn")
  like_btn.addEventListener("click",(e)=>{
    e.preventDefault
    console.log("123")
    like_btn.textcontent="yes"
  })
</script> %>